name: Stats

on: pull_request

jobs:
  # Builds current master. Should be entirely cached most of the time!
  build-master:
    if: contains(github.event.pull_request.labels.*.name, 'stats-pls')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
      # Get the base ref
      - name: Fetch target branch
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
          git checkout ${{ github.base_ref }}
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build
        run: ./gradlew :app:assembleRelease -x lintVitalRelease -PuseDebugSigning=true
      - name: Move apk
        run: mv app/build/outputs/apk/release/catchup-universal-release.apk release-${{ github.base_ref }}.apk
      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: apks
          path: '*.apk'

  # Builds the current PR
  build-pr:
    if: contains(github.event.pull_request.labels.*.name, 'stats-pls')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build
        run: ./gradlew :app:assembleRelease -x lintVitalRelease -PuseDebugSigning=true
      - name: Move apks
        run: mv app/build/outputs/apk/release/catchup-universal-release.apk release-${{ github.sha }}.apk
      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: apks
          path: '*.apk'

  # Diffs the master and PR APKs, uploads the full diff to the PR, and comments a short diff to it
  # Only runs if the label 'stats" is applied
  diff-apks:
    if: contains(github.event.pull_request.labels.*.name, 'stats-pls')
    needs: [build-pr, build-master]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: jakewharton/diffuse
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 1.8
      - name: Build diffuse
        run: ./gradlew assemble
      - name: Download apks
        uses: actions/download-artifact@v2
        with:
          name: apks
      - name: Run diffuse
        run: |
          ls -al
          ./diffuse/build/diffuse diff release-${{ github.base_ref }}.apk release-${{ github.sha }}.apk > apk-diff-${{ github.base_ref }}-${{ github.sha }}.txt
      - name: Prepare PR comment
        run: printf "### Δ Diffuse stats for \`$(echo ${GITHUB_BASE_REF} | cut -c1-7)\` ➡ $(echo ${GITHUB_SHA} | cut -c1-7) Δ\n\n\`\`\`\n" > pr-comment.txt && sed '/====   DEX   ====/q' apk-diff-${{ github.base_ref }}-${{ github.sha }}.txt | tac | sed "1,2d" | tac | sed -e :a -e '/^\n*$/{$d;N;};/\n$/ba' >> pr-comment.txt && echo "\`\`\`"  >> pr-comment.txt
      - name: Comment PR
        uses: machine-learning-apps/pr-comment@1.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          path: pr-comment.txt
      - name: Upload full diff
        uses: actions/upload-artifact@v2
        with:
          name: apk-diffs
          path: apk-diff-${{ github.base_ref }}-${{ github.sha }}.txt
